version: "3.8"

services:
  app:
    build: .
    container_name: express-library-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/local_library
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: express-library-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
